import { Geist, Geist_Mono } from "next/font/google";
import styles from "./page.module.css";
import Link from "next/link";
import "./global.css";
import { Links } from "./links";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  const id = 5;
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Links />
        {children}
      </body>
    </html>
  );
}
